#!/usr/bin/env python3
"""Regenerates src/SKLWebConsolePage.h from page/console.html.

Run after editing the page:   python3 tools/embed_page.py
The page is gzipped (the firmware serves it with Content-Encoding: gzip), so
it costs a few KB of flash and loads fast over a weak device WiFi link.
"""
import gzip
from pathlib import Path

root = Path(__file__).resolve().parent.parent
src = root / "page" / "console.html"
dst = root / "src" / "SKLWebConsolePage.h"

raw = src.read_bytes()
# mtime=0 keeps the output byte-for-byte stable, so git diffs only show real changes.
gz = gzip.compress(raw, compresslevel=9, mtime=0)

lines = []
for i in range(0, len(gz), 20):
    lines.append("  " + ", ".join(f"0x{b:02x}" for b in gz[i:i + 20]) + ",")

dst.write_text(
    "// GENERATED by tools/embed_page.py from page/console.html -- do not edit by hand.\n"
    f"// {len(raw)} bytes of HTML, {len(gz)} bytes gzipped.\n"
    "#pragma once\n"
    "#include <Arduino.h>\n\n"
    f"static const size_t SKL_WEBCONSOLE_PAGE_GZ_LEN = {len(gz)};\n"
    "static const uint8_t SKL_WEBCONSOLE_PAGE_GZ[] PROGMEM = {\n"
    + "\n".join(lines)
    + "\n};\n",
    newline="\n",
)
print(f"{dst.relative_to(root)}: {len(raw)} -> {len(gz)} bytes")
